# Generated by Django 4.1.3 on 2024-03-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='category',
        ),
    ]
