# Generated by Django 4.1.3 on 2024-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
